In [44]:
import cv2
import mediapipe as mp
import math
import numpy as np
from time import sleep
# from ffpyplayer.player import MediaPlayer
# from mediapipe.python.solutions import hands

In [45]:
def dist(x1,y1,x2,y2): # 비교를 위한 거리 계산 함수
    return math.sqrt( math.pow(x1-x2,2) + math.pow(y1-y2,2))

In [46]:
compareIndex = [[18,4],[6,8],[10,12],[14,16],[18,20]] # 마디 index 번호
hand_open = [False,False,False,False,False] # False로 초기화
gesture = [
    [False,True,True,False,False,"Yeah"],
    [True,False,False,False,False,"Good"],
]

In [47]:
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
mpHands = mp.solutions.hands
my_hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

# 첫번째 영상

In [121]:
#control frame rate
cap = cv2.VideoCapture('../sample_dance/dyna1_30.mp4') # jupyter 
# cap = cv2.VideoCapture('./sample_dance/videoplayback.mp4') # vs

#cap = cv2.VideoCapture('C:/Users/yoond/바탕 화면/00CAPSTONE/Capstone-Design/DAIN/sample_dance/videoplayback.mp4')
fps = cap.get(cv2.CAP_PROP_FPS)

frame_counter = 0
frameTime = int((1/fps)*1000)  #time of each frame (ms단위, 몇ms당 1frame으로 할지 설정)
print(fps)
extract_time_by_per_frame = 1 #몇프레임 당 한번 측정할지 조절 가능


30.0


In [122]:
# ###start step2 --> 영상 추출
# #extract_file = open('DAIN/extractsamples/result.txt','w')
# cap = cv2.VideoCapture('../sample_dance/videoplayback.mp4') # jupyter 
# # cap = cv2.VideoCapture('./sample_dance/videoplayback.mp4') # vs

# #cap = cv2.VideoCapture('C:/Users/yoond/바탕 화면/00CAPSTONE/Capstone-Design/DAIN/sample_dance/videoplayback.mp4')
# fps = cap.get(cv2.CAP_PROP_FPS)



result = np.array([]) # 추출된 영상의 전체 넘파이 배열
bone_index = [11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28] # 필요한 관절 번호


with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        frame_counter += 1 #increase frame counter

        #Recolor image to RGB
        if ret:
            if frame_counter % extract_time_by_per_frame == 0:
                image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                image.flags.writeable = False

                #Detection
                results = pose.process(image)

                #Recolor image RGB to BGR
                image.flags.writeable = True
                image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

                #Extract landmarks
                try: #success to extract landmarks
                    landmarks = results.pose_landmarks.landmark
                    
                    ret = []
                    
                    # # 11 12 13 14 15 16 23 24 25 26 27 28
                    for i in bone_index: # 필요한 부분의 관절의 정보만
                        temp = np.array([landmarks[i].x,landmarks[i].y,landmarks[i].z], float)
                        ret = np.append(ret,temp,axis = 0)
                        
                        
#                     for i in range(len(landmarks)):
#                         temp = np.array([landmarks[i].x,landmarks[i].y,landmarks[i].z], float)
#                         ret = np.append(ret,temp,axis = 0)
                    
                    #print(ret)
                    result = np.append(result,ret,axis=0)
                    #print("extracting\n")
                except:
                    pass
        
        else: #no next frame (end point of video)
            break
            #Show video on screen
        cv2.imshow('dance_file',frame)
        
        if cv2.waitKey(frameTime) & 0xFF == 27:
            break

    cap.release()
    cv2.destroyAllWindows()
    #extract_file.close()





In [123]:
print('*****extract success*****')
z = result.shape[0]/(len(bone_index)*3)
result = np.reshape(result,(int(z),len(bone_index),3)) # frame 수,  tracking좌표 수, xyz 
print(result[0])
print(result.shape)

*****extract success*****
[[ 0.46507198  0.3546381   0.06392627]
 [ 0.53517652  0.35496491 -0.06406817]
 [ 0.46453208  0.44917837  0.11296497]
 [ 0.53740734  0.46542028 -0.06063438]
 [ 0.47957745  0.4979032   0.17253238]
 [ 0.54777753  0.54769289 -0.01412602]
 [ 0.48015919  0.55657172  0.03743545]
 [ 0.51852137  0.56020677 -0.0373728 ]
 [ 0.47822624  0.70837885  0.04842366]
 [ 0.50764787  0.71957946 -0.01146149]
 [ 0.48129281  0.85916233  0.09490544]
 [ 0.49353781  0.87991816  0.02743725]]
(312, 12, 3)


In [124]:
print(len(result))

312


# body index
body_index = [
    
    [11,13,15], # left arm
    [12,14,16], # right arm
    [23,25,27], # left leg
    [24,26,28], # right leg
    
    [14,12,24],
    [13,11,23],
    [23,24,26],
    [24,23,25],
    
]
l1 = result[0][11]
l2 = result[0][13]
l3 = result[0][15]


ll1 = l1-l2
ll2 = l3-l2

innerAB = np.dot(ll1,ll2)
AB = np.linalg.norm(ll1) * np.linalg.norm(ll2)
angle = np.arccos(innerAB/AB)
print(angle) # radian
print(angle/np.pi*180)

# 두번째 영상

In [125]:
#control frame rate
cap = cv2.VideoCapture('../sample_dance/dyna2.mp4') #('../../HSLEE/demo/dance/sample.mp4') # jupyter 
# cap = cv2.VideoCapture('./sample_dance/videoplayback.mp4') # vs

#cap = cv2.VideoCapture('C:/Users/yoond/바탕 화면/00CAPSTONE/Capstone-Design/DAIN/sample_dance/videoplayback.mp4')
fps = cap.get(cv2.CAP_PROP_FPS)

frame_counter = 0
frameTime = int((1/fps)*1000)  #time of each frame (ms단위, 몇ms당 1frame으로 할지 설정)
print(fps)
extract_time_by_per_frame = 1 #몇프레임 당 한번 측정할지 조절 가능


30.0


In [126]:
# ###start step2 --> 영상 추출
# #extract_file = open('DAIN/extractsamples/result.txt','w')
# cap = cv2.VideoCapture('../sample_dance/videoplayback.mp4') # jupyter 
# # cap = cv2.VideoCapture('./sample_dance/videoplayback.mp4') # vs

# #cap = cv2.VideoCapture('C:/Users/yoond/바탕 화면/00CAPSTONE/Capstone-Design/DAIN/sample_dance/videoplayback.mp4')
# fps = cap.get(cv2.CAP_PROP_FPS)



user_video_result = np.array([]) # 추출된 영상의 전체 넘파이 배열


with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        frame_counter += 1 #increase frame counter

        #Recolor image to RGB
        if ret:
            if frame_counter % extract_time_by_per_frame == 0:
                image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                image.flags.writeable = False

                #Detection
                results = pose.process(image)

                #Recolor image RGB to BGR
                image.flags.writeable = True
                image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

                #Extract landmarks
                try: #success to extract landmarks
                    landmarks = results.pose_landmarks.landmark
                    
                    ret = []
                    
                    # # 11 12 13 14 15 16 23 24 25 26 27 28
                    for i in bone_index: # 필요한 부분의 관절의 정보만
                        temp = np.array([landmarks[i].x,landmarks[i].y,landmarks[i].z], float)
                        ret = np.append(ret,temp,axis = 0)
                        
                        
#                     for i in range(len(landmarks)):
#                         temp = np.array([landmarks[i].x,landmarks[i].y,landmarks[i].z], float)
#                         ret = np.append(ret,temp,axis = 0)
                    
                    #print(ret)
                    user_video_result = np.append(user_video_result,ret,axis=0)
                    #print("extracting\n")
                except:
                    pass
        
        else: #no next frame (end point of video)
            break
            #Show video on screen
        cv2.imshow('dance_file',frame)
        
        if cv2.waitKey(frameTime) & 0xFF == 27:
            break

    cap.release()
    cv2.destroyAllWindows()
    #extract_file.close()





In [127]:
print('*****extract success*****')
z = user_video_result.shape[0]/(len(bone_index)*3)
user_video_result = np.reshape(user_video_result,(int(z),len(bone_index),3)) # frame 수,  tracking좌표 수, xyz 
print(user_video_result[0])
print(user_video_result.shape)

*****extract success*****
[[ 0.45640907  0.52090657 -0.021587  ]
 [ 0.50814033  0.51846415 -0.03642946]
 [ 0.46140724  0.61364704 -0.02786098]
 [ 0.50287867  0.61906171 -0.0586761 ]
 [ 0.47413212  0.66606671 -0.02912012]
 [ 0.51249516  0.67429352 -0.05859148]
 [ 0.47191724  0.69402885 -0.00483433]
 [ 0.50038564  0.69343954  0.00485449]
 [ 0.47499809  0.82567322  0.02512417]
 [ 0.49559537  0.82578433  0.02651009]
 [ 0.4776004   0.95226687  0.05504317]
 [ 0.4945775   0.95147789  0.04697707]]
(314, 12, 3)


In [128]:
len(user_video_result)

314

In [129]:
body_index = [
    [0,2,4], # left arm
    [1,3,4], # right arm
    [6,8,10], # left leg
    [7,9,11], # right leg

    [3,1,7],
    [2,0,6],
    [6,7,9],
    [7,6,8],
]

In [130]:
# user_video_result = result # 녹화된 비디오
total_point = 0 # 총 포인트

# 프레임 수가 작은 것을 기준으로 
length = len(result)
print(length)

if( len(result) >= len(user_video_result)):
    length = len(user_video_result)
    print(len(user_video_result))

print(length)

312
312


In [137]:


for n in range(length-1, -1, -1):
        
    for index in body_index:
        l1 = result[n][index[0]]
        l2 = result[n][index[1]]
        l3 = result[n][index[2]]

        ll1 = l1-l2
        ll2 = l3-l2
        
        innerREAL = np.dot(ll1,ll2)
        REAL = np.linalg.norm(ll1) * np.linalg.norm(ll2)
        angleREAL = np.arccos(innerREAL/REAL)/np.pi*180
        #print(angleREAL/np.pi*180)


        u1 = user_video_result[n][index[0]]
        u2 = user_video_result[n][index[1]]
        u3 = user_video_result[n][index[2]]

        uu1 = u1-u2
        uu2 = u3-u2
        
        innerUSER = np.dot(uu1,uu2)
        USER = np.linalg.norm(uu1) * np.linalg.norm(uu2)
        angleUSER = np.arccos(innerUSER/USER)/np.pi*180
        #print(angleUSER)


        if angleUSER <= angleREAL + 30.0 and angleUSER >= angleREAL - 30.0:
            total_point+=1
            
 # 8 : 비교 각도의 개수 len(result) : frame 개수

In [138]:
print(total_point)
print((total_point / (8 * length ) * 100))

8280
331.7307692307692


for num, r in enumerate(result):
    
    for index in body_index:
        l1 = r[index[0]]
        l2 = r[index[1]]
        l3 = r[index[2]]
        
        ll1 = l1-l2
        ll2 = l3-l2
        
        innerAB = np.dot(ll1,ll2)
        AB = np.linalg.norm(ll1) * np.linalg.norm(ll2)
        angle = np.arccos(innerAB/AB)
        print(angle/np.pi*180)
    
    print('\n')
    
    